export const artists = [
    // Currently waiting for drop
    {address: 'tz1aBgHQm9KrJ4WrZkfkzS6BEykYbDXP8znU', alias: 'Marcin Ignac', gas: 1, maxCost: 50, mintAmount: 0}, //cycle 81 1400 UTC
    {address: 'tz1aNZttacWt7Q2kmvDnLjXkxC27MnigTZtV', alias: 'DistCollective', gas: 0.1, maxCost: 8, mintAmount: 2}, //cycle 80
    {address: 'tz1ZaJJmi8suCPWBUnW2WrJRcP59ybLaqonH', alias: 'NeedleUnderNail', gas: 0.1, maxCost: 15, mintAmount: 0}, //cycle 81 1314 UTC
    {address: 'tz1YbJAyfmSwqLbLwCrUTfEMeLgCncM9jj3z', alias: 'Empress Trash', gas: 0.1, maxCost: 10, mintAmount: 0}, //not sure on date yet



    // Always on
    {address: 'tz1gBXG9fg8RMDH69KfKqwoTH5sFDmzt5yzm', alias: 'Zancan', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz1dgXcFWb6F4F1ohd34k62KTmAfT6W1yKNb', alias: 'Zach Lieberman', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz1XHADaUcMSkTN9gdmtRqcnrrZfs4tNkCPg', alias: 'Matt DesLauriers', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz1Kw8cEFuNLj21e5b42NBn1ANW7hupmbDbo', alias: 'Piter Pasma', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz1eJF2r9JsfDLAswoo5iCDk6Qv2yWt6fbMX', alias: 'William Mapan', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1dEF5ZMTnBSkz2ZQPvpJjwyfeUUyGjeMtf', alias: 'ertdfgcvb', gas: 2, maxCost: 0, mintAmount: 0},
    {address: 'tz1YHsinBJHMj1YFN7UrCsVAgTcaJCH86PjK', alias: 'Rudxane', gas: 0, maxCost: 0, mintAmount: 0},
    {address: 'tz1bzg9xNB4heuF41sLfrdt1QmqrJTDQqDwN', alias: 'MJ Lindow', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1PoDdN2oyRyF6DA73zTWAWYhNL4UGr3Egj', alias: 'Ciphrd', gas: 2, maxCost: 0, mintAmount: 0},
    {address: 'tz1LBwyJMRkH4tcG19KwYzAW7fLYbjFmWdWy', alias: 'Raes', gas: 0.75, maxCost: 0, mintAmount: 0},
    {address: 'tz1gVKxpEGC7QW1fZyEEMEW2kgJRbpgWLNpD', alias: 'Iskra', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz2Pkj2xWJovKKCsABjnr3NbyMVJTMBkpTvb', alias: 'Thomas Lin Pedersen', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz1TxDL7npfYDSyvrZFC4deUPMySvsL6xARU', alias: 'p1xelfool', gas: 1, maxCost: 0, mintAmount: 0},

    // BIG ARTISTS
    /*

    {address: 'tz1P8QWLVevt9ECbf4khYyAuQLzRmPD2vYZq', alias: '1mposter', gas: 2, maxCost: 0, mintAmount: 0},
    {address: 'tz1hx7d1qWCHkSDy6HXVmZRzWvpNMHxSNvuC', alias: '1mposter2', gas: 2, maxCost: 0, mintAmount: 0},
    {address: 'tz1NMvVB48fNzrG3rPZS58Eo1nSJ6p3RjRyz', alias: 'Hevey', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1d4ThofujwwaWvxDQHF7VyJfaeR2ay3jhf', alias: 'Toxi', gas: 1, maxCost: 20, mintAmount: 0},
    {address: 'tz1WopvVxCVdGP7Sew7kz6Kro9o1qQ7SuEtN', alias: 'Che-Yu Wu', gas: 0.75, maxCost: 0, mintAmount: 0},
    {address: 'tz1WKofYY1qf3eiXfVduycVVtvJDvVjBuV9j', alias: 'random_combo', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1N1vuWBsDtGMyj3No8NfeJdCBFu8v6gvSX', alias: 'Kim Asendorf', gas: 0.75, maxCost: 25, mintAmount: 0},
    {address: 'tz1amcnQuDXY2pzBy23e4sV8qaxpRbQAY7W6', alias: 'Michael Connolly/xiiixiii', gas: 0.75, maxCost: 0, mintAmount: 0},
    {address: 'tz1ZMDCUyEvsQykWuxTkBzVDcTzMtUEwTeiw', alias: 'Presstube', gas: 0.75, maxCost: 0, mintAmount: 0},
    {address: 'tz1Y7XasjwFn64jufhDNvh5HrUMUx59hLR67', alias: 'perkwerk', gas: 0.11, maxCost: 0, mintAmount: 0},
    {address: 'tz2MgAiWfd5i7kee4pMKiY5cx5QQUHD94HFS', alias: 'Ippsketch', gas: 0.76, maxCost: 0, mintAmount: 0},
    {address: 'tz1KgQPu6JSgppkWCUBcqP9RFYhXKfCeDSG3', alias: 'Eko33', gas: 0.76, maxCost: 0, mintAmount: 0},
    {address: 'tz1eCX4smQ3LbxwDR3pqNoLQvNNKiHJtpwYz', alias: 'Msoriaro', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1TSWEDs9wcBx2KiRzVzyzECsNpRiZaLJ1D', alias: 'Wblut', gas: 1, maxCost: 20, mintAmount: 0},
    {address: 'tz1QgjmhrUD3X7kgS9mMHbUz4cS6uDiFGhAU', alias: 'yazid', gas: 0.1, maxCost: 0, mintAmount: 0},
    {address: 'tz1Roq6end2LFtkpGrmuyRZH82xsWfaRCat1', alias: 'Andreas Rau', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1cbhmVZuFTKHcACSFpg5ER1bGVGkanhrbW', alias: 'Ileivoivm', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1YZ4VZCRPoiDyGP3U69jCq2S8duDUcRjHP', alias: 'Loren Bednar', gas: 0.75, maxCost: 0, mintAmount: 0},
    {address: 'tz2KDeWyeCeu2eZYLav9PrRAQmFCyESNF4Es', alias: 'Jacek Markusiewicz/mrkswcz', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1QAevDTqQ92FWh7fXrS6esiFmFgnsEqi1b', alias: 'Julien Espagnon', gas: 0.5, maxCost: 0, mintAmount: 0},
    {address: 'tz1dFcfEbAb9abXBEXERV4uMv48e4x17MuBb', alias: 'nbswwit', gas: 0.1, maxCost: 0, mintAmount: 0},
    {address: 'tz2VN3fWzqHE44F6zedJB7UtALKEh5WhqAJJ', alias: 'Makio', gas: 0.1, maxCost: 0, mintAmount: 0},
    {address: 'tz1WqBtWEXjYPwKofxDPsf2V8Jo7dRxdKYqu', alias: 'Shvembldr', gas: 0.75, maxCost: 25, mintAmount: 0},
    {address: 'tz1QxDQFtjzn7q851vx1McZ6DnJZtbJ8eaxc', alias: 'Pizza Punk', gas: 0.1, maxCost: 0, mintAmount: 0},
    {address: 'tz1WJpiJkNoMEjXE1wvoKeRuZo4o9Zgy6qXe', alias: 'Yi-Wen Lin', gas: 0.12, maxCost: 0, mintAmount: 0},
    {address: 'tz1Z2kdYtxZ6YAYyCTYZUmEwvXJbdjN7mdzs', alias: 'Amy Goodchild', gas: 0.1, maxCost: 0, mintAmount: 0},
    {address: 'tz1UPfsrzqrJ2DrYnZdrVsjBohtxxyQ8fK2e', alias: 'Nadieh Bremer', gas: 0.1, maxCost: 10, mintAmount: 0},
    {address: 'tz2PsPRLTf3NPp43MqnHvWz1Q2URYQtisxs2', alias: 'Goldcat', gas: 0.1, maxCost: 0, mintAmount: 0},
    {address: 'tz1XuoTxu2m7Kdp5iBhLv35KxFcjkoeY5vYe', alias: 'Jinyao Lin', gas: 0.75, maxCost: 20, mintAmount: 0},
    {address: 'tz1aLCW57GTwnmBNcrwWUR2y4YUEQAFGQYtU', alias: 'Ivona Tau', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz29mS5gdfemxdhTZbtksFj5atKKLfJ8JM3D', alias: 'Julien Gachadoat', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1aBgHQm9KrJ4WrZkfkzS6BEykYbDXP8znU', alias: 'Marcin Ignac', gas: 0.5, maxCost: 0, mintAmount: 0},
    {address: 'tz1iZ2TPEShFC8TqHsXLA9RXdV7tSv8E3aLe', alias: 'jjjjohn fx', gas: 3, maxCost: 0, mintAmount: 0},
    {address: 'tz1dKjizZy6FxZaYuaK6HM8Xx3yP558MwaAp', alias: 'pixeldealer', gas: 2, maxCost: 0, mintAmount: 0},

    */

    // Great artists but not as big
    /*

    {address: 'tz1c3HNFnE14bTcRHpiqPWNXv7wPpgcTwKF5', alias: 'Vectris', gas: 0.26, maxCost: 10, mintAmount: 0},
    {address: 'tz2XS9YK749k4SZ61SgyEsqei2Q8AuUzxody', alias: 'Lucas Reveil', gas: 0.5, maxCost: 0, mintAmount: 0},
    {address: 'tz1gYwgGhpxjt4po3f53P1t1sS3osPondHwW', alias: 'Lomz', gas: 0, maxCost: 5, mintAmount: 1},
    {address: 'tz1Wzwn5KCCnf12wCX9LAPrd9uYR8iPDNSx3', alias: 'Lars Wander', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz29rT6LwCuZcyxkJ3mNvFNSRBryfxnPZqJW', alias: 'Cyril Diagne', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1ZhM6cK59xj8Uw7tLDihsxhAdWaKsGFXKy', alias: 'CNZA', gas: 0, maxCost: 2, mintAmount: 0},
    {address: 'tz1i5qkVbi55gLVXLZXyQwjVMfuQnSgri8LN', alias: 'Itu', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1WhX3XRDvbJf4XY87Zh6JRstmqcjpM1Hfs', alias: 'Lisa Orth', gas: 0, maxCost: 2, mintAmount: 0},
    {address: 'tz1PhYXjxJJovmLLuajAa4kYACQXE2eVEF5k', alias: 'Jeff Palmer', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1T5NfkdPfhkXzYx8akPkdznxSgU1Uf5jEG', alias: 'josefluispelz', gas: 0.15, maxCost: 5, mintAmount: 0},
    {address: 'tz1PADW67gHdeXY8mxmM13vn7V7oXvW8MgPr', alias: 'Eltono', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1ZNeKWirU5UsUYY24da22RAp51XVvaUckz', alias: 'p4stoboy', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1W6tnKqKVf4XPeBpMDSzMAt63XYPN7SZG9', alias: 'Danda Odara', gas: 0.01, maxCost: 10, mintAmount: 0},
    {address: 'tz1aARx1r9qzScEmRXNxY5WpKzL6ebWrWjMD', alias: 'Pablo Alpe', gas: 1, maxCost: 10, mintAmount: 0},
    {address: 'tz1iQYj4WTf4Wv5Rrs2X3RCgu5WpfgNsdTYr', alias: 'Lunin', gas: 0.1, maxCost: 1, mintAmount: 0},
    {address: 'tz1NgKMZKDXCCLVRkr9uPG5JL3BUZ4TNYXc6', alias: 'Ed Cavett', gas: 0.1, maxCost: 5, mintAmount: 1},
    {address: 'tz2RTSZwShS8sMrZeiwBgcEV1pHmXdr24Ta8', alias: 'gpitombo', gas: 0.1, maxCost: 10, mintAmount: 0},
    {address: 'tz1WEZkz46AZmGbW32qwUHsdA2PBBATgixth', alias: 'Camille Roux', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1LhoBCe6e3wM5LRqyXBX8DjZnKNg5ybGsu', alias: 'Stephen Jue', gas: 0, maxCost: 8, mintAmount: 0},
    {address: 'tz2V1jTtkUjZzWVgcfLcg6S4XxtSJo7PyLYN', alias: 'pxlshrd', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1NgN7FCrSzs4vfMroKXyKE32WsReYD4WPd', alias: 'loackme', gas: 0, maxCost: 10, mintAmount: 1},
    {address: 'tz1X6QwMBuVooaG7kFxCCe7iLVcMwAZvJz6r', alias: '0xGeo', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1aB4WhspBPfLA6X4qSQPZCDKQkmmGobrCk', alias: 'ismahelio', gas: 0.75, maxCost: 15, mintAmount: 0},
    {address: 'tz2KKNQKxfnH9BDkWaRWaumUdnN2F8J5dxHe', alias: 'waxhead', gas: 0, maxCost: 10, mintAmount: 1},
    {address: 'tz1i7fDupvRU8AWoQgPtqJvKivXnyvuvTLYN', alias: 'Leander Herzog', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1Zy9Dvfx7fYsQzvZPPzTxAQWGXx7RKgZ7v', alias: 'balidani', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1eketDCA9TNj3njKjwc7hbbmWq9Pp4w2eJ', alias: 'Jonathan Murillo', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1boJei5NMkmgcorY9VAwtNVMQgUfWt5arj', alias: 'VanTa', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1TrP5wSFiujdFbamzSwRGopufeTqGDWYMi', alias: 'Patricio Isaias', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1LhhLW2rtGaTvLLZHrngNBxmnLbQsBvQM5', alias: 'erfan hoseini', gas: 0, maxCost: 10, mintAmount: 2},
    {address: 'tz1c3HNFnE14bTcRHpiqPWNXv7wPpgcTwKF5', alias: 'Vectris', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1gqMsumVLf3jukknYJZCpkz9Psxsb81iZa', alias: 'Rezva', gas: 0.75, maxCost: 10, mintAmount: 0},
    {address: 'tz1cX25wPQbDoecNqWXScwZ24GTBj4ixpQLA', alias: '0rfula', gas: 0.1, maxCost: 5, mintAmount: 2},
    {address: 'tz1bnWUvcfU77EBpbLUQ41c3hCBKovGuqyGY', alias: 'Krankarta', gas: 0.1, maxCost: 5, mintAmount: 2},
    {address: 'tz1XK1NVQXhwdGFdZvdodVyos1osAu7LTNLi', alias: 'abstractment', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1h3Cz9aMM6aiNbfPhybev6o9KCfY8geaPd', alias: 'Aleksandra', gas: 0, maxCost: 10, mintAmount: 1},
    {address: 'tz2VFQNZrRk3PMxR725wxXB8b5dqFnNoWbog', alias: 'lleixa', gas: 0, maxCost: 15, mintAmount: 1},
    {address: 'tz1hf7a8ueUyHvjAZ4VhxUGAnGfhvTmnffyw', alias: 'nudoru', gas: 0, maxCost: 15, mintAmount: 1},
    {address: 'tz1SkJMvMBtmsrUMNY2gCEf6SBAt76AWBKzz', alias: 'EverlastingBuilding', gas: 0, maxCost: 15, mintAmount: 2},
    {address: 'tz1egC68FQ5iMt7C5DRtr8pzVDBLLz9Qh8HT', alias: 'Park Hyun', gas: 0, maxCost: 5, mintAmount: 2},
    {address: 'tz1hKZ3scdxqd2UC6nFDyyyNQW659YyeYrQQ', alias: 'idflood', gas: 0.1, maxCost: 15, mintAmount: 0},
    {address: 'tz1ipr6o23Pb6jvfpJrrgkbhxbRBmYbmQn81', alias: 'Florian Zumbrunn', gas: 0, maxCost: 5, mintAmount: 1},
    {address: 'tz1XMYyXTn3FmnJKJGh55ivepRPqNpQqeE7x', alias: 'Studio Yorktown', gas: 0, maxCost: 5, mintAmount: 1},
    {address: 'tz1N3wxmggKeyaAMpVsKZAZNGDUDq5vdPG5E', alias: 'Peter Ravnborg', gas: 0, maxCost: 5, mintAmount: 1},
    {address: 'tz1Qvc8ocPr2C1UuwyAH1uaXvDiFxWWDjXHo', alias: 'LittleSilver', gas: 0, maxCost: 5, mintAmount: 1},
    {address: 'tz1Rakav1r6xMmrvYiXZjdvz3T1wNU4igoQM', alias: 'lunarean', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz2EoVjpjbuuy6QigakPsjz1Ms3maSchUhrs', alias: 'laxraven', gas: 0.1, maxCost: 10, mintAmount: 0},
    {address: 'tz1LhNHNiLyHpmfAXkp56sqLM19n9kn2Sw16', alias: 'Nat Sarkissian', gas: 0.1, maxCost: 10, mintAmount: 0},
    {address: 'tz1NfU86mDijR5C1U2WAitJJTbbnCxmnr9Bd', alias: 'Tu.ukz', gas: 0.1, maxCost: 5, mintAmount: 1},
    {address: 'tz1b1EAJskrdbdD2vhr2xoLkTLpowvAgK1Tk', alias: '3DManatee', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1dDLPtaFAspKoiyMzhhRmxJ3dh2oSJvA69', alias: 'Gendoodler', gas: 0.11, maxCost: 5, mintAmount: 0},
    {address: 'tz1ZWrGRL8CmWXAtR38TwCha1aTUq6mPgJrJ', alias: 'Artik', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1ZEoCxEKW6fPZv8LZrpu2N6DBZcCCqMS6v', alias: 'Andre Fuchs', gas: 0, maxCost: 1, mintAmount: 0},
    {address: 'tz1RkYY3jr1ocuPdQqrRefr5FqoawKQsmBmD', alias: 'Landlines Art', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1i7tKfmok8uX9VhaZZSoxbMGVYgXcPSb6U', alias: 'Geoff Stearns', gas: 0, maxCost: 3, mintAmount: 0},
    {address: 'tz1eJF2r9JsfDLAswoo5iCDk6Qv2yWt6fbMX', alias: 'nicthib', gas: 0, maxCost: 5, mintAmount: 0},
    {address: 'tz1ibTknNagJCgQPgcbPvJhpSyS5vxgdyFt4', alias: 'Chris Randall', gas: 0, maxCost: 3, mintAmount: 1},
    {address: 'tz2At5T1CLTcoF97ScUcbrekeHdPXwvQ3yWt', alias: 'Dorian Lods', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1hLchXK8YvpNcJhDAC4Sw3JiPUMzuCDQf5', alias: 'Baltazagarden', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1e1VQwX91Z9fB64yt3j9b6912JbEnMi28P', alias: 'Georgios', gas: 0, maxCost: 10, mintAmount: 2},
    {address: 'tz1TtZmtxhiWc8Nv6AtC1YjVCtJoFjv4nTqL', alias: 'Dehiscence', gas: 0, maxCost: 10, mintAmount: 0},
    {address: 'tz1YbJAyfmSwqLbLwCrUTfEMeLgCncM9jj3z', alias: 'Empress Trash', gas: 0.1, maxCost: 10, mintAmount: 0},
    {address: 'tz1T55y8BEuXQrCzBaPqayugNNGFwxy27WJt', alias: 'Flockaroo', gas: 0.1, maxCost: 20, mintAmount: 0},
    {address: 'tz1XLoRoxUzDHj63gQjZfvA2XpPium5nmYYg', alias: 'Philip Bell', gas: 0.1, maxCost: 20, mintAmount: 0},
    {address: 'tz1aNZttacWt7Q2kmvDnLjXkxC27MnigTZtV', alias: 'DistCollective', gas: 0.1, maxCost: 20, mintAmount: 0},
    {address: 'tz1ZaJJmi8suCPWBUnW2WrJRcP59ybLaqonH', alias: 'NeedleUnderNail', gas: 0.1, maxCost: 20, mintAmount: 0},

    */

    // Artists that have a tezos address but have not been seen on fxhash and probably won't ever mint anything
    {address: 'tz1R8kQK1CR59su3GYpPBFHxrBokNPYWaM42', alias: 'xcopy', gas: 5, maxCost: 0, mintAmount: 0},
    {address: 'tz1R5aLedcRQb9kYyNBS1UXzHR6aQQ3Z5qoq', alias: 'Sutu', gas: 3, maxCost: 41, mintAmount: 0},
    {address: 'tz1gqaKjfQBhUMCE6LhbkpuittRiWv5Z6w38', alias: 'jjjjjohn', gas: 5, maxCost: 0, mintAmount: 0},
    {address: 'tz1MLPBC5zEbhojkcN7CervtG7eGbCeKvRB3', alias: 'jjjjjohn 2', gas: 5, maxCost: 0, mintAmount: 0},
    {address: 'tz1cNFGNAQrFQucdvc4txsdR8rEuHkUUYrjJ', alias: 'Max Capacity', gas: 0.7, maxCost: 41, mintAmount: 0},
    {address: 'tz1fEivXU93hFAthx3oT5xEqWFeh3TwZZmdz', alias: 'Max Capacity 2', gas: 0.7, maxCost: 41, mintAmount: 0},
    {address: 'tz1Zs2WDRv9549rnHkjAjdMaWXVnreixXVKD', alias: 'whatisreal', gas: 3, maxCost: 41, mintAmount: 0},
    {address: 'tz1SjtzTd8GSm4PhZC7xjmTniysrNbeTFNFf', alias: 'fvckrender', gas: 5, maxCost: 0, mintAmount: 0},
    {address: 'tz2KbXVAfzDw8JX3WVTPjgePrqtPYQiUmyc4', alias: 'LuisPonce', gas: 3, maxCost: 41, mintAmount: 0},
    {address: 'tz1auPyXVaMy3GntdCQwH2VGNuFj6bAocj2v', alias: 'Lia Something', gas: 0.25, maxCost: 31, mintAmount: 0},
    {address: 'tz1XbQMwcJkZynP5qajqwqMC1vd96Pc1oS97', alias: 'EsoTeros', gas: 1, maxCost: 0, mintAmount: 0},
    {address: 'tz1RNDoqLh5VCqBUXrgmzhwxqcR7ptAfvfNh', alias: 'Lucrece', gas: 5, maxCost: 0, mintAmount: 0},
    {address: 'tz1V58uyGexjsN8HFguTkP4H2Ps1y5g99Jtp', alias: 'Heart You', gas: 5, maxCost: 31, mintAmount: 0},
    {address: 'tz1biKU3xnysM6WXAYN9Qsp9siv8Ttz5f7UY', alias: 'omgidrawedit', gas: 5, maxCost: 41, mintAmount: 0},
    {address: 'tz1f4V314WFsUzYwVBudTLN7nPoB79HZKsdD', alias: 'Kristen Roos', gas: 0.25, maxCost: 0, mintAmount: 0},
    {address: 'tz1S7NKRdKnh5SKuKpQTz3XCvpctF218ewKF', alias: 'Pierre Casadebaig', gas: 2, maxCost: 0, mintAmount: 0},
];